on:
  push:
    tags:
      - 'm*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show tag
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          echo $RELEASE_VERSION
          echo '${{ github.ref_name }}' ${{ github.ref_name }}
